flej3/Dong_a_ri_Da_rak_bang

app/app.js
app/package-lock.json
app/package.json
app/src/controllers/login.ctrl.js
app/src/controllers/register.ctrl.js
app/src/controllers/token.ctrl.js
app/src/routes/pages-login.route.js
app/src/views/assets/js/login.js
app/src/views/ejs-file/pages-login.ejs
app/src/views/ejs-file/partials/header.ejs

Login front back

---

app/app.js
app/src/config/database.func.js
app/src/controllers/clubAdmin.ctrl.js
app/src/controllers/index.ctrl.js
app/src/controllers/login.ctrl.js
app/src/controllers/tokenControllers/token.ctrl.js
app/src/routes/index.route.js
app/src/routes/pages-clubAdmin.route.js
app/src/views/ejs-file/pages-clubAdmin.ejs
app/src/views/ejs-file/partials/header.ejs
app/src/views/ejs-file/partials/sideBar.ejs

지금 병합된 작업 내용.
1. 동아리 관리자 권한이 있는 사람 (club테이블에 등록된 사람)은 
아래 스크린샷처럼 동아리 관리 페이지를 열수있고 볼수있음.
2. 동아리 관리자 권한이 없는 계정은 다른 2번 스크린샷처럼 동아리 관리 페이지를 
열수도 없고 볼수도 없음.
3. 헤더에서 로그인시 사용자의 이름이 출력됌
=> "어드민님 안녕하세요!"
4. 1번 2번 이 사이드바 메뉴에서도 동일하게 적용됌.
5. 사이드바에서 기존에 로그인으로만 뜨던 메뉴를 로그인 여부에 따라
로그인 또는 로그아웃으로 변경되서 작동함.
###작업내용이 좀 많아서 버그가 있을수 있습니다! 작업하시다가 버그 발견해주시면 말씀해주세요##

Login header whit jwt

---

app/src/controllers/clubAdmin.ctrl.js
app/src/controllers/index.ctrl.js

oner->owner 

---

app/app.js
app/src/config/database.func.js
app/src/controllers/searchCtrollers/searchUser.ctrl.js
app/src/routes/search/search.route.js
app/src/views/assets/css/style.css
app/src/views/assets/js/profile/profile_view.js
app/src/views/assets/js/search/header_search.js
app/src/views/assets/js/search/user_search_profile.js
app/src/views/assets/js/search/user_search_result.js
app/src/views/ejs-file/pages-search/search-result.ejs
app/src/views/ejs-file/pages-search/user_search_profile.ejs
app/src/views/ejs-file/partials/header.ejs
app/src/views/ejs-file/users-profile.ejs

검색창에서 유저를 검색하고 해당 프로필로 이동하는 로직 구현 완료

User search

---

app/src/controllers/searchCtrollers/searchUser.ctrl.js
app/src/views/ejs-file/users-profile.ejs

member테이블의 category -> club_join으로 수정에 따른 수정과, profile 동아리 관리 데모 추가
DB 테이블의 컬럼명 변경에 따른 패치와 Profile 동아리 관리 텝에 데모 버전 추가.

member테이블의 category -> club_join으로 수정에 따른 수정과, profile 동아리 관리 데모 추가

---

app/src/views/assets/js/post/post-recruit/viewPost.js

게시글 작성하고 들어가서 보았을때 텍스트 정렬 기능이 안되어서 수정했습니다.(왼쪽, 중간, 오른쪽) 정렬

게시글 작성하고 들어가서 보았을때 텍스트 정렬 기능이 안되어서 수정했습니다.(왼쪽, 중간, 오른쪽) 정렬

---

app/src/controllers/register.ctrl.js
app/src/routes/pages-register.route.js
app/src/views/assets/css/style.css
app/src/views/assets/js/login.js
app/src/views/assets/js/register.js
app/src/views/ejs-file/pages-login.ejs
app/src/views/ejs-file/pages-register.ejs

<스펙>
1. 로그인창에서 로그인 실패시 아래 경고문구가 반짝이는 액션 추가, 로그인창 한국어 적용.
2. 회원가입 리팩토링, + 한국어 적용.
새롭게 적용된 학번을 기입하는 규칙!
2-1. 9자리를 원칙으로 합니다. (ex. 201955005)
2-2. 이미 DB member테이블에 있는 학번으로는 가입이 불가능합니다.
3. DB에 정해놓은 양보다 많은양의 글자를 넣었을때 문제가 생길수도 있어서 입력제한을 걸었습니다.
4. 전화번호를 입력중 공백과 '-'문자는 자동으로 제외되서 DB에 들어갑니다.
5. 이전보다 회원가입 창을 더 확실하고 정확하게 검사합니다.

로그인창, 회원가입, 학번 중복 방지. 

---

app/src/views/ejs-file/users-profile.ejs

마이프로필 페이지에서 하단에 이상한 마진이 있던걸 수정함

마이프로필 페이지에서 하단에 이상한 마진이 있던걸 수정함

---

app/app.js
app/src/controllers/create-club.ctrl.js
app/src/routes/pages-create-club.route.js
app/src/views/assets/js/createClub/createClub.js
app/src/views/assets/js/createClub/modalCreateClubView.js
app/src/views/assets/js/post/index.postDashboard.js
app/src/views/ejs-file/pages-create-club.ejs
app/src/views/ejs-file/partials/sideBar.ejs

Create club logic

---

app/src/views/assets/js/pagesAdmin/club_recruit_tab.js

최신 게시글이 맨 위로 오도록 수정

---

app/src/views/assets/js/pagesAdmin/club_recruit_tab.js
app/src/views/ejs-file/pages-clubAdmin.ejs

동아리 관리 페이지에 모집공고 탭에 페이지네이션 기능 추가

동아리 관리 페이지에 모집공고 탭에 페이지네이션 기능 추가

---

app/src/controllers/clubAdminControllers/clubNoticePost.ctrl.js
app/src/routes/pages-clubAdmin.route.js
app/src/views/assets/js/pagesAdmin/admin_edit.js
app/src/views/assets/js/pagesAdmin/club_notice_tab.js
app/src/views/ejs-file/pages-clubAdmin.ejs

<동아리 관리 페이지 - 공지 사항 탭 스펙>
1. 해당 공지 사항은 공지 사항 텝에서 "작성하기" 버튼을 통해 작성을 할 수 있습니다.
1-1. 공지사항 작성은 동아리 회장(대표)만 가능합니다.
2. 공지사항 탭에 작성된게 없으면 "작성된 공지사항이 없습니다." 라는 카드가 뜹니다.
3. 해당 공지사항 카드를 클릭하면 공지사항의 내용을 담은 모달이 뜹니다.
4. 공지사항 삭제, 수정 버튼은 club_member 테이블에 admin_ac가 있는 유저만 버튼이 뜹니다.
5. 수정 버튼을 누르면 해당 공지사항의 내용을 가져온뒤에 그 이후부터 이어서 수정이 가능합니다.
6. 삭제 버튼을 누르면 정말 삭제할건지 물어보고난뒤 삭제 확인 모달에서 "확인" 버튼을 누르면 삭제가 됩니다.
7. 해당 공지사항이 5개가 넘어가면 나머지 카드는 다음 페이지로 넘어갑니다.

공지 사항 탭 기능 구현 완료

---

app/src/views/assets/css/style.css
app/src/views/assets/js/post/index.postDashboard.js

대시보드에 띄워지는 게시글 카드에 마감일과 마감 여부를 뱃지로 띄워주도록 수정 하였습니다.

메인 대시보드의 게시글에 마감일, 마감여부 ui 출력

---

app/src/controllers/clubAdminControllers/clubProfileControllers/clubProfile.ctrl.js
app/src/routes/page-club-profile/page-club-profile.route.js
app/src/views/assets/js/clubProfile/clubProfile.js
app/src/views/assets/js/pagesAdmin/club_notice_tab.js
app/src/views/ejs-file/page-club-profile/page-club-profile.ejs

<동아리 탈퇴 로직 구현 완료: 스팩>
1. 동아리 탈퇴는 http://127.0.0.1:3000/club-profile 해당 페이지에서 가능합니다.
2. 회장은 탈퇴가 불가능합니다. 
-> 성영님이 이후에 구현해주시는 회장 권한 위임을 하고난뒤 진행 가능.
3. 회장을 제외한 인원은 모두 동아리 탈퇴가 가능합니다!

동아리 탈퇴 로직 구현 완료

---

app/src/views/ejs-file/partials/sideBar.ejs

sidebar 버그 수정

---

app/app.js
app/src/controllers/clubIntroductionControllers/clubIntroduction.ctrl.js
app/src/routes/clubIntroduction/pages-clubIntroduction.route.js
app/src/views/assets/js/clubProfile/clubProfile.js
app/src/views/assets/js/club_list.js
app/src/views/assets/js/pagesAdmin/admin_edit.js
app/src/views/assets/js/pagesAdmin/club_introduction.js
app/src/views/ejs-file/page-club-introduction/page-club-introduction.ejs
app/src/views/ejs-file/pages-clubAdmin.ejs
app/src/views/ejs-file/pages-clubList.ejs

동아리 관리 페이지에서 탭들중에 "동아리 소개 편집" 탭이 추가 되었습니다.

1차 동아리 소개 페이지 동아리 소개 탭 기능 추가.

---

app/src/views/assets/js/createClub/modalCreateClubView.js

동아리 생성|등록 페이지에서 신청한 동아리 목록이 최신이 가장 위로 올라오도록 수정

동아리 생성|등록 페이지에서 신청한 동아리 목록이 최신이 가장 위로 올라오도록 수정

---

app/src/views/assets/js/pagesAdmin/admin_edit.js

콘솔에 버그 수정 
student-id와 ph-number를 못찾아서 뜨는 오류 수정.

개발자 도구 콘솔에 뜨던 오류 수정(기존 해당 요소 id를 못찾아서 뜨던 에러)

---

app/src/views/assets/css/style.css
app/src/views/assets/js/clubIntroPage/clubIntroRecruitTab.js
app/src/views/assets/js/login.js

동아리 소개 탭의 모집 공고 ui 수정과 로그인 성공시 뜨던 alert 삭제

동아리 소개 탭의 모집 공고 ui 수정과 로그인 성공시 뜨던 alert 삭제

---

app/src/controllers/clubAdminControllers/clubDelete.ctrl.js
app/src/routes/pages-clubAdmin.route.js
app/src/views/assets/js/pagesAdmin/delete_club.js
app/src/views/ejs-file/pages-clubAdmin.ejs

동아리 대표인지 확인하는 API 개발

---

app/src/controllers/postCtrollers/index.postDashboard.ctrl.js
app/src/controllers/postCtrollers/postRecruitControllers/viewPost.ctrl.js
app/src/routes/post/index.postDashboard.route.js
app/src/routes/post/postRecruit/view-post.route.js
app/src/views/assets/js/pagesAdmin/admin_edit.js
app/src/views/assets/js/post/index.postDashboard.js
app/src/views/assets/js/post/post-recruit/viewPost.js
app/src/views/ejs-file/index.ejs
app/src/views/ejs-file/pages-clubAdmin.ejs
app/src/views/ejs-file/post/post-recruit/view-post.ejs

좋아요 api 추가 등

---

app/src/views/assets/js/post/post-recruit/viewPost.js

비로그인시 랜더링을 로그인 화면으로 변경

---

app/src/controllers/clubAdmin.ctrl.js
app/src/views/assets/js/post/index.postDashboard.js
app/src/views/assets/js/post/post-recruit/viewPost.js
app/src/views/assets/js/search/header_search.js

console.log 제거

---

app/src/controllers/clubAdmin.ctrl.js
app/src/controllers/clubIntroductionControllers/clubIntroduction.ctrl.js
app/src/routes/clubIntroduction/pages-clubIntroduction.route.js
app/src/views/assets/js/clubIntroPage/clubs_introduction.js
app/src/views/assets/js/pagesAdmin/admin_edit.js
app/src/views/ejs-file/page-club-introduction/page-club-introduction.ejs

- 회원 삽입 오류 수정
- 동아리 소개 페이지 그래프 삽입
- 권한 위임 버튼 오류 수정

그래프 작업 및 ctrl 오류 수정

---

app/app.js
app/src/controllers/userActive.ctrl.js
app/src/routes/user-active.route.js
app/src/views/assets/js/users_active.js
app/src/views/ejs-file/partials/sideBar.ejs
app/src/views/ejs-file/users-active.ejs

내 활동 내역 페이지

---

app/src/controllers/clubAdmin.ctrl.js
app/src/routes/pages-clubAdmin.route.js
app/src/views/assets/js/pagesAdmin/admin_club_applications.js
app/src/views/assets/js/pagesAdmin/admin_edit.js

club table member_count 칼럼 동적 변경 작업입니다.

회원 추가, 가입 승인 시 member_count update

---

app/src/controllers/postCtrollers/postRecruitControllers/writePost.ctrl.js
app/src/routes/post/postRecruit/write-post.route.js
app/src/views/assets/css/style.css
app/src/views/assets/js/post/post-recruit/editPost.js
app/src/views/assets/js/post/post-recruit/writePost.js
app/src/views/ejs-file/post/post-recruit/edit-post.ejs
app/src/views/ejs-file/post/post-recruit/write-post.ejs

<클라우드 스토리지를 활용한 게시글 Fix>
1. 게시글 작성하기와 편집하기 UI가 변경 되었습니다.
=>
기존) quill 에디터를 통한 이미지 삽입 (base64 형태로 DB에 기입)
변경) 클릭 또는 드래그&드랍 으로 사진을 첨부 하면 해당 이미지가 클라우드에 저장됌.
2. DB에는 클라우드에 저장된 이미지 경로가 들어가서 저장됩니다.
3. 이미지를 삽입하면 본문의 가장 최상단에 이미지가 들어갑니다.
4. 이미지를 삽입하면 해당 이미지가 클라우드에 올라가기까지 시간이 걸리는데 그때 로딩바가 나옵니다.

Add cloudinary storage api

---

app/src/controllers/clubAdmin.ctrl.js
app/src/views/assets/js/pagesAdmin/admin_edit.js

- 관리자 페이지 회원정보 삽입, 변경 시 오류 발생 해결 작업

회원 업데이트 오류 수정

---

app/src/views/ejs-file/index.ejs

메인 대시보드에 동아리 생성하기 카드 구현

---

app/src/views/assets/js/post/index.postDashboard.js

메인 대시보드에서 모집중, 마감됨 텝에서 비로그인시 API 호출에서 에러가 뜨던 오류를 수정 했습니다.

메인 대시보드에서 모집중, 마감됨 텝에서 비로그인시 API 호출에서 에러가 뜨던 오류를 수정 했습니다.

---

app/src/views/assets/js/post/post-recruit/join_club/index.clubJoinDashboard.js

메인 대시보드에서 신청중인 동아리 목록에서 신청중인 동아리 목록 테이블이 안나오는 버그를 수정했습니다.

메인 대시보드에서 신청중인 동아리 목록에서 신청중인 동아리 목록 테이블이 안나오는 버그를 수정했습니다.

---

app/src/views/ejs-file/pages-faq.ejs

FAQ 작업(feedback 우선)

---

app/src/views/assets/js/post/index.postDashboard.js

메인 대시보드에서 로그인을 해도 좋아요를 누른 게시글의 하트가 활성화 안되던 버그를 수정했습니다.

메인 대시보드에서 로그인을 해도 좋아요를 누른 게시글의 하트가 활성화 안되던 버그를 수정했습니다.

---

app/src/views/assets/js/clubProfile/clubProfile.js

탈퇴 update 추가

---

app/src/views/assets/js/clubProfile/clubProfile.js
app/src/views/ejs-file/page-club-profile/page-club-profile.ejs

동아리 프로필 페이지에서 고유 영역 지정해서 UI 안깨지게 수정.

동아리 프로필 페이지에서 고유 영역 지정해서 UI 안깨지게 수정.

---

app/src/views/assets/js/post/index.postDashboard.js

기존에 메인대시보드 게시글의 메인 사진이 기본값이였는데 클라우드 연동하여서 동적으로 뿌려주게 변경 하였습니다.

기존에 메인대시보드 게시글의 메인 사진이 기본값이였는데 클라우드 연동하여서 동적으로 뿌려주게 변경 하였습니다.

---

app/src/views/assets/js/profile/headerProfileImg.js

비로그인 상태에서 게시글을 보려고 들어가면 에러가 뜨던 버그 수정

비로그인 상태에서 게시글을 보려고 들어가면 에러가 뜨던 버그 수정

---

app/app.js
app/src/controllers/find-ID-PW/findIdPw.ctrl.js
app/src/routes/find-ID-PW/page-find-id-pw.route.js
app/src/views/assets/js/findIdPw.js
app/src/views/ejs-file/pages-findIdPw.ejs
app/src/views/ejs-file/pages-login.ejs

<ID, 비밀번호 찾기 로직>
1. 로그인 창에서 하단에 ID, 비밀번호 찾기 가 추가되었습니다.
2. 해당 버튼을 누르면 ID찾기와 비밀번호 찾기를 사용할 수 있습니다.
3. ID는 일정 값만 입력하면 바로 찾을수 있습니다.
4. 비밀번호는 오픈 카카오톡으로 본인인증을 해야만 운영진이 본인인증 코드를 주고 그 코드를 입력하면 인증코드에 해당하는 아이디의 비밀번호를 변경할 수 있습니다.

아이디, 비밀번호 찾기 로직 구현 완료

---

app/src/controllers/searchCtrollers/searchUser.ctrl.js
app/src/views/assets/js/search/user_search_result.js

헤더에 유저 검색할때 없는 유저를 검색했을때 뜨는 오류를 처리

헤더에 유저 검색할때 없는 유저를 검색했을때 뜨는 오류를 처리

---

app/src/controllers/searchCtrollers/searchUser.ctrl.js
app/src/views/assets/js/search/user_search_result.js

헤더에 유저를 검색했을때 유저가 검색이 안되던 버그 수정

헤더에 유저를 검색했을때 유저가 검색이 안되던 버그 수정
